---
title: "Assignment_2"
author: "Clara Ferrer Castellà"
date: "4 de mayo de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("ggplot2")
library("grid")
library("gridExtra")
library("scales")
library("plyr")
library("corrplot")
library("gbm")
library("caret")
library("tidyr")
library("dplyr")
library("unbalanced")

```


```{r}
# Stablishing the working directory and the file paths 
Working_directory <- setwd("~/DM_Basic_Assignment/Assignment_2")
d <- unzip("Assignment2_data.zip")
file_training <- file.path(Working_directory, "Data Mining VU data" , "training_set_VU_DM_2014.csv")
file_test <- file.path(Working_directory, "Data Mining VU data" , "test_set_VU_DM_2014.csv")



# Opening the files 
all_train <- read.csv(file_training, header = TRUE)
#test <- read.csv(file_test, header = TRUE)


```



```{r}

all_train <- all_train %>%
  group_by(srch_id)

all_length <- nrow(all_train)
splity <- all_length*0.15
test <- all_train[1:splity,]
splited_train <- all_train[(splity+1):all_length,]


rm(all_train)

#Second split of the data
dt <- sort(sample(nrow(splited_train), nrow(splited_train)*.82353)) #to have 15% of the real_train.
train <- splited_train[dt,]
validation <- splited_train[-dt,]
#Deletin of the not useful variables
rm(splited_train, dt)
rm(splity, all_length)

 

```


```{r}
# Create the unknown colum 
train$unknown_bool <- ifelse(train$click_bool == 0 & train$booking_bool == 0, 1, 0) 

# Visualization of the unbalanced data

train[c("click", "booking", "unknown")] <- as.factor(train[c("click_bool", "booking_bool", "unknown_bool")]) # Group the data based on "click_bool", "booking_bool", "unknown_bool" variables using dplyr package containing "group by" function


```



```{r}
data(ubIonosphere)
n <- ncol(ubIonosphere)
output <- ubIonosphere[ ,n]
input <- ubIonosphere[ ,-n]
#apply oversampling
data <- ubBalance(X=input, Y=output, type="ubOver", k=0)
#oversampled dataset
overData <- data.frame(data$X, Class=data$Y)
#check the frequency of the target variable after oversampling
summary(overData$Class)



#Balance the data

train.test$unknown_bool <- ifelse(train.test$click_bool == 0 & train.test$booking_bool == 0, 1, 0) 

n <- ncol(train.test[c("click_bool", "booking_bool", "unknown_bool")])

input <- train.test[ , n]
output <- na.omit(train.test[ , -n])
 
#apply undersampling
data <- ubBalance(X=input, Y=as.factor(output), type="ubUnder", perc=100,  method="percPos")
#undersampled dataset
underData <- data.frame(data$X, Class=data$Y)
#check the frequency of the target variable after oversampling
summary(underData$Class)

```

