---
title: "DMTA2"
author: "S"
date: "14 de mayo de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Before start:

* Clean the Environment
```{r}
rm(list=ls())
```

* Set path
```{r}
setwd("C:/Users/SILVIA TOSHIBA/Documents/MASTER/Data mining techniques/Assignment 2/Data")
```

* Load Packages
```{r}
library(ggplot2)
library(dplyr)
library(unbalanced)
```

* Functions definition
```{r}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

Load the data
```{r}
#Load the data
#all_train <- read.csv("train.csv", header = TRUE)
#real_test <- read.csv("test.csv", header = TRUE)

#LOAD A SUBSET OF THE DATA FOR MY OWN COMPUTER, NOT ABLE TO LOAD THE WHOLE DATA
all_train <- read.csv("train.csv",header=TRUE, nrows = 100000)
#real_test <- read.csv("train.csv",header=TRUE, nrows = 1000)
```

Visualize the Data
Visualization of the new hotels
```{r}
# Change the NAs to character to be taken into account in the plot
all_train$prop_review_score[is.na(all_train$prop_review_score)] <- "NA"

# Plot of the Hotel rating score for all hotels
p1 <- ggplot(all_train, aes(x=prop_review_score)) + geom_bar() + ggtitle("A") + xlab("Hotel Review Score")

# Plot of the score of the booked hotels, to see if the users prefer a new hotel (NA) or a hotel with the woorst case scenario (0)
pre_NA_visual <-table(Rating=all_train$prop_review_score, Booked= as.logical(all_train$booking_bool))
pre_NA_visual <- as.data.frame(prop.table(pre_NA_visual, 1)) # row percentages 
NA_visual <- pre_NA_visual[pre_NA_visual$Rating=="NA"| pre_NA_visual$Rating=="0",]
NA_visual <- NA_visual[NA_visual$Booked==TRUE,]

p2 <- ggplot(NA_visual, aes(x = Rating, y = Freq)) + 
  geom_bar(stat = "identity", position = position_dodge()) + 
  ggtitle("B") + xlab("Hotel Review Score")

multiplot(p1, p2, cols=2)

# Remove useless Data from Envirinment
rm(NA_visual, p1, p2, pre_NA_visual)
```

Unbalanced data
```{r}
# Create the ignored column
all_train$ignored_bool <- ifelse(all_train$click_bool == 0 & all_train$booking_bool == 0, 1, 0)

balance_visual <- data.frame(Type = c("click","book", "ignored"), Value=c(sum(all_train$click_bool==1), sum(all_train$booking_bool==1), sum(all_train$ignored_bool==1)))

ggplot(balance_visual, aes(x=Type, y=Value, fill=Type)) + 
  geom_histogram(stat="identity")

# balance_visual <- data.frame(Yes=c(sum(train$click_bool==1), sum(train$booking_bool==1), sum(train$ignored_bool==0)), No = c(sum(train$click_bool==0), sum(train$booking_bool==0), sum(train$ignored_bool==1)), row.names = c("click","book", "ignored"))
# 
# balance_visual <- as.matrix(balance_visual)
# balance_visual <- as.table(balance_visual)
# 
# percentage_balance <- as.data.frame(prop.table(balance_visual, 1)*100) # row percentages 
# 
# 
# ggplot(percentage_balance, aes(x = Var2, y = Freq, fill = Var1)) + 
#   geom_bar(stat = "identity", position = position_dodge())

# Remove useless Data from Envirinment
rm(balance_visual,NA_visual,pre_NA_visual)
```

Split in Train, Test and Validation set
```{r}
#Group by search ID to then split the test set
all_train <- all_train %>%
  group_by(srch_id)

#Split of the test set
all_length <- nrow(all_train)
splity <- all_length*0.15
test <- all_train[1:splity,]
splited_train <- all_train[(splity+1):all_length,]
# Modify number of cucus depending on the srch_id cutoff
rm(all_train) 

#Split the validation set
dt <- sort(sample(nrow(splited_train), nrow(splited_train)*.82353)) #to have 15% of the real_train
train <- splited_train[dt,]
validation <- splited_train[-dt,]

# Remove useless Data from Envirinment
rm(splited_train, dt)
rm(splity, all_length)
```

Data Balance
```{r}
#library(unbalanced)

train$ignored_bool <- ifelse((train$click_bool == 0 & train$booking_bool == 0), 0, 1)

input <- train
output <- as.factor(train$ignored_bool)

#balance the dataset
function_output<-ubBalance(X=input, Y=output, perc=40, type = "ubUnder")
underTrain<-data.frame(function_output$X)

#Visualize de balance
unbalance_visual <- data.frame(Type = c("Click","Book", "Ignored"), Value=c(sum(train$click_bool==1), sum(train$booking_bool==1), sum(train$ignored_bool==0)))

p1 <- ggplot(unbalance_visual, aes(x=Type, y=Value, fill=Type)) + 
  geom_histogram(stat="identity", show.legend = FALSE) +
  ggtitle("Unbalanced Data")

balance_visual <- data.frame(Type = c("Click","Book", "Ignored"), Value=c(sum(underTrain$click_bool==1), sum(underTrain$booking_bool==1), sum(underTrain$ignored_bool==0)))

p2 <- ggplot(balance_visual, aes(x=Type, y=Value, fill=Type)) + 
  geom_histogram(stat="identity", show.legend = FALSE) +
  ggtitle("Balanced Data")

multiplot(p1, p2, cols=2)

# Remove useless Data from Envirinment
rm(balance_visual, function_output, input, unbalance_visual, p1, p2, output)
```

```{r}
#TEST BALANCE
test$ignored_bool <- ifelse((test$click_bool == 0 & test$booking_bool == 0), 0, 1)

inputT <- test
outputT <- as.factor(test$ignored_bool)

#balance the dataset
function_outputT<-ubBalance(X=inputT, Y=outputT, perc=40, type = "ubUnder")
underTest<-data.frame(function_outputT$X)

#VALIDATION BALANCE
validation$ignored_bool <- ifelse((validation$click_bool == 0 & validation$booking_bool == 0), 0, 1)

inputV <- validation
outputV <- as.factor(validation$ignored_bool)

#balance the dataset
function_outputV<-ubBalance(X=inputV, Y=outputV, perc=40, type = "ubUnder")
underValidation<-data.frame(function_outputV$X)

#Remove the useless variables
rm(inputT,outputT, function_outputT, inputV, outputV, function_outputV)
```

```{r}
#Remove the unbalanced variables
rm(train, test, validation)

# Re-change the ignored variable
underTrain$ignored_bool <- ifelse((underTrain$click_bool == 0 & underTrain$booking_bool == 0), 1, 0)
underTest$ignored_bool <- ifelse((underTest$click_bool == 0 & underTest$booking_bool == 0), 1, 0)
underValidation$ignored_bool <- ifelse((underValidation$click_bool == 0 & underValidation$booking_bool == 0), 1, 0)
```

